[package]
name = "midi_var"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fundsp = {git = "https://github.com/SamiPerttu/fundsp"}
midir = "0.8"
cpal = "0.14"
anyhow = "1"
midi-msg = "0.4"
read_input = "0.8"