[package]
name = "midi_fundsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fundsp = "0.10"
midir = "0.8"
cpal = "0.14"
anyhow = "1"
midi-msg = "0.4"
bare_metal_modulo = "1"
crossbeam-queue = "0.3"

[dev-dependencies]
read_input = "0.8"
